version: '2.1'
services:
  db:
    image: mongo:latest
    ports:
     - "27017:27017"
    volumes_from:
        - db-data
    networks:
      snomed:
        aliases:
         - db

  db-data:
    image: mongo:latest
    volumes:
      - ~/mongo/data:/data/db
      - ~/mongo/lib:/var/lib/mongodb
      - ~/mongo/log:/var/log/mongodb
    entrypoint: /bin/true

  snomed-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: snomed-api:latest
    links:
      - db
    ports:
      - "9999:9999"
      - "35729:35729"
    environment:
      - NODE_ENV=development
      - MONGO_DB_CONN=db:27017
      - SCT_VERSION=20180131
      - PORT=9999
    networks:
      - snomed

networks:
  snomed:
    driver: bridge
